apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sentiment-analysis-deployment
  labels:
    app: my-sentiment-analysis-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-user-api
  template:
    metadata:
      labels:
        app: my-user-api
    spec:
      containers:
      - name: my-user-api
        image: datascientest/exam-k8s-jeffmac-userapi:1.0.0
        ports:
        - containerPort: 8000
      - name: the-database
        image: datascientest/mysql-k8s:1.0.0
        ports:
        - containerPort: 9000
	env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-datascientest-rootpass
              key: password
